const ACTION_TYPES = {
	TEST_CONNECTION: "TEST_CONNECTION",
	TEST_CONNECTION_IN_PROGRESS: "TEST_CONNECTION_IN_PROGRESS",
	TEST_CONNECTION_FAILED: "TEST_CONNECTION_FAILED",
	TEST_CONNECTION_SUCCEEDED: "TEST_CONNECTION_SUCCEEDED",
};

const types = { ...ACTION_TYPES };

export default types;